;
; File generated by cc65 v 2.19 - Git b1e1c13
;
	.fopt		compiler,"cc65 v 2.19 - Git b1e1c13"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.export		_iochip
	.export		_kbmem
	.export		_dispcard
	.export		_musiccard
	.export		_drivecard
	.export		_cursorX
	.export		_cursorY
	.export		_dispChar
	.export		_ti
	.export		_printText
	.export		_setCursor
	.export		_drivebuf
	.export		_drivebuf1
	.export		_busyWait
	.export		_drqWait
	.export		_readDiskInfo
	.export		_initStartSector
	.export		_readDiskBuf
	.export		_readSector
	.export		_setMusicReg
	.export		_delay
	.export		_playSong
	.export		_main

.segment	"DATA"

_iochip:
	.word	$B000
_kbmem:
	.word	$7F00
_dispcard:
	.word	$8000
_musiccard:
	.word	$9000
_drivecard:
	.word	$A000
_cursorX:
	.byte	$00
_cursorY:
	.byte	$00

.segment	"RODATA"

_ps2ToAscii:
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$09
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$7F
	.byte	$00
	.byte	$7E
	.byte	$2B
	.byte	$31
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$7A
	.byte	$73
	.byte	$61
	.byte	$2A
	.byte	$32
	.byte	$00
	.byte	$00
	.byte	$63
	.byte	$78
	.byte	$64
	.byte	$65
	.byte	$34
	.byte	$33
	.byte	$00
	.byte	$00
	.byte	$20
	.byte	$76
	.byte	$66
	.byte	$74
	.byte	$72
	.byte	$35
	.byte	$00
	.byte	$00
	.byte	$6E
	.byte	$62
	.byte	$68
	.byte	$67
	.byte	$79
	.byte	$36
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$6D
	.byte	$6A
	.byte	$75
	.byte	$37
	.byte	$38
	.byte	$00
	.byte	$00
	.byte	$2C
	.byte	$6B
	.byte	$69
	.byte	$6F
	.byte	$30
	.byte	$39
	.byte	$00
	.byte	$00
	.byte	$2E
	.byte	$2F
	.byte	$6C
	.byte	$3B
	.byte	$70
	.byte	$2D
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$69
	.byte	$00
	.byte	$5B
	.byte	$3D
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$0A
	.byte	$5D
	.byte	$00
	.byte	$5C
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$08
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$7D
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
_text:
	.byte	$36,$35,$30,$32,$20,$53,$42,$43,$20,$28,$56,$2E,$50,$43,$42,$29
	.byte	$20,$6D,$61,$6E,$69,$65,$6B,$38,$36,$20,$28,$63,$29,$20,$32,$30
	.byte	$32,$34,$0A,$59,$4D,$20,$44,$69,$73,$6B,$20,$50,$6C,$61,$79,$65
	.byte	$72,$20,$76,$31,$0A,$00

.segment	"BSS"

_ti:
	.res	1,$00
_drivebuf:
	.res	512,$00
_drivebuf1:
	.res	512,$00

; ---------------------------------------------------------------
; void __near__ dispChar (char c)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_dispChar: near

.segment	"CODE"

	jsr     pusha
	lda     _dispcard+1
	sta     ptr1+1
	lda     _dispcard
	sta     ptr1
	ldy     #$00
	lda     (sp),y
	sta     (ptr1),y
	inc     _cursorX
	lda     _cursorX
	cmp     #$50
	bcs     L0006
	lda     (sp),y
	cmp     #$0A
	bne     L0005
L0006:	sty     _cursorX
	lda     _cursorY
	cmp     #$3B
	bcs     L0005
	inc     _cursorY
L0005:	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; void __near__ printText (const char *text)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_printText: near

.segment	"CODE"

	jsr     pushax
	lda     #$00
	sta     M0001
L0009:	lda     M0001
	cmp     #$7F
	bcs     L0003
	ldy     #$01
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     M0001
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	beq     L0003
	ldy     #$01
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     M0001
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	jsr     _dispChar
	inc     M0001
	jmp     L0009
L0003:	jmp     incsp2

.segment	"BSS"

M0001:
	.res	1,$00

.endproc

; ---------------------------------------------------------------
; void __near__ setCursor (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_setCursor: near

.segment	"CODE"

	lda     _dispcard+1
	sta     ptr1+1
	lda     _dispcard
	sta     ptr1
	ldy     #$01
	tya
	sta     (ptr1),y
	lda     _dispcard+1
	sta     ptr1+1
	lda     _dispcard
	sta     ptr1
	lda     _cursorX
	dey
	sta     (ptr1),y
	lda     _dispcard+1
	sta     ptr1+1
	lda     _dispcard
	sta     ptr1
	iny
	lda     #$02
	sta     (ptr1),y
	lda     _dispcard+1
	sta     ptr1+1
	lda     _dispcard
	sta     ptr1
	lda     _cursorY
	dey
	sta     (ptr1),y
	lda     _dispcard+1
	sta     ptr1+1
	lda     _dispcard
	sta     ptr1
	iny
	lda     #$00
	sta     (ptr1),y
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ busyWait (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_busyWait: near

.segment	"CODE"

L0002:	lda     _drivecard
	ldx     _drivecard+1
	ldy     #$07
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	sta     M0001
	and     #$80
	bne     L0002
	lda     M0001
	and     #$40
	beq     L0002
	rts

.segment	"BSS"

M0001:
	.res	1,$00

.endproc

; ---------------------------------------------------------------
; void __near__ drqWait (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_drqWait: near

.segment	"CODE"

L0002:	lda     _drivecard
	ldx     _drivecard+1
	ldy     #$07
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	sta     M0001
	lsr     a
	lsr     a
	lsr     a
	and     #$01
	beq     L0002
	rts

.segment	"BSS"

M0001:
	.res	1,$00

.endproc

; ---------------------------------------------------------------
; void __near__ readDiskInfo (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_readDiskInfo: near

.segment	"CODE"

	lda     #$00
	sta     M0001
	sta     M0001+1
	lda     #$0A
	jsr     _dispChar
	lda     _drivecard+1
	sta     ptr1+1
	lda     _drivecard
	sta     ptr1
	ldy     #$06
	lda     #$E0
	sta     (ptr1),y
	lda     _drivecard+1
	sta     ptr1+1
	lda     _drivecard
	sta     ptr1
	iny
	lda     #$EC
	sta     (ptr1),y
	jsr     _busyWait
	jsr     _drqWait
	lda     #$00
	sta     M0001
	sta     M0001+1
L0004:	lda     M0001
	cmp     #$00
	lda     M0001+1
	sbc     #$02
	bvc     L0008
	eor     #$80
L0008:	bpl     L0018
	lda     _drivecard+1
	sta     ptr1+1
	lda     _drivecard
	sta     ptr1
	ldy     #$00
	lda     (ptr1),y
	sta     M0002
	lda     M0001
	clc
	adc     #<(_drivebuf)
	sta     sreg
	lda     M0001+1
	adc     #>(_drivebuf)
	sta     sreg+1
	lda     _drivecard
	ldx     _drivecard+1
	ldy     #$08
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	ldy     #$00
	sta     (sreg),y
	inc     M0001
	bne     L000B
	inc     M0001+1
L000B:	lda     M0001
	clc
	adc     #<(_drivebuf)
	sta     ptr1
	lda     M0001+1
	adc     #>(_drivebuf)
	sta     ptr1+1
	lda     M0002
	sta     (ptr1),y
	inc     M0001
	bne     L0004
	inc     M0001+1
	jmp     L0004
L0018:	lda     #$0A
	jsr     _dispChar
	jsr     _setCursor
	ldx     #$00
	lda     #$36
	sta     M0001
	stx     M0001+1
L000C:	lda     M0001
	cmp     #$5C
	lda     M0001+1
	sbc     #$00
	bvc     L0010
	eor     #$80
L0010:	bpl     L0019
	lda     M0001
	sta     ptr1
	lda     M0001+1
	clc
	adc     #>(_drivebuf)
	sta     ptr1+1
	ldy     #<(_drivebuf)
	lda     (ptr1),y
	jsr     _dispChar
	inc     M0001
	bne     L000C
	inc     M0001+1
	jmp     L000C
L0019:	lda     #$0A
	jsr     _dispChar
	jsr     _setCursor
L0012:	lda     _drivecard
	ldx     _drivecard+1
	ldy     #$07
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	sta     M0003
	lsr     a
	lsr     a
	lsr     a
	and     #$01
	beq     L001A
	lda     _drivecard+1
	sta     ptr1+1
	lda     _drivecard
	sta     ptr1
	ldy     #$00
	lda     (ptr1),y
	sta     M0002
	lda     #$2E
	jsr     _dispChar
	jmp     L0012
L001A:	lda     #$4B
	jmp     _dispChar

.segment	"BSS"

M0001:
	.res	2,$00
M0002:
	.res	1,$00
M0003:
	.res	1,$00

.endproc

; ---------------------------------------------------------------
; void __near__ initStartSector (unsigned int sectorNum)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_initStartSector: near

.segment	"CODE"

	jsr     pushax
	lda     _drivecard+1
	sta     ptr1+1
	lda     _drivecard
	sta     ptr1
	ldy     #$00
	lda     (sp),y
	ldy     #$03
	sta     (ptr1),y
	lda     _drivecard
	ldx     _drivecard+1
	clc
	adc     #$04
	bcc     L0003
	inx
L0003:	sta     ptr1
	stx     ptr1+1
	ldy     #$01
	lda     (sp),y
	dey
	sta     (ptr1),y
	lda     _drivecard+1
	sta     ptr1+1
	lda     _drivecard
	sta     ptr1
	ldy     #$05
	lda     #$00
	sta     (ptr1),y
	lda     _drivecard+1
	sta     ptr1+1
	lda     _drivecard
	sta     ptr1
	iny
	lda     #$E0
	sta     (ptr1),y
	lda     _drivecard+1
	sta     ptr1+1
	lda     _drivecard
	sta     ptr1
	ldy     #$02
	lda     #$01
	sta     (ptr1),y
	lda     _drivecard+1
	sta     ptr1+1
	lda     _drivecard
	sta     ptr1
	ldy     #$07
	lda     #$20
	sta     (ptr1),y
	jmp     incsp2

.endproc

; ---------------------------------------------------------------
; void __near__ readDiskBuf (unsigned char buf)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_readDiskBuf: near

.segment	"CODE"

	jsr     pusha
	lda     _drivecard
	ldx     _drivecard+1
	ldy     #$07
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	sta     M0002
	jsr     _drqWait
	ldy     #$00
	lda     (sp),y
	bne     L0018
	sta     M0001
	sta     M0001+1
L0004:	ldx     M0001+1
	cpx     #$02
	jcs     L000D
	lda     M0001
	clc
	adc     #<(_drivebuf)
	sta     sreg
	lda     M0001+1
	adc     #>(_drivebuf)
	sta     sreg+1
	lda     _drivecard+1
	sta     ptr1+1
	lda     _drivecard
	sta     ptr1
	lda     (ptr1),y
	sta     (sreg),y
	inc     M0001
	bne     L0009
	inc     M0001+1
L0009:	lda     M0001
	clc
	adc     #<(_drivebuf)
	sta     sreg
	lda     M0001+1
	adc     #>(_drivebuf)
	sta     sreg+1
	lda     _drivecard
	ldx     _drivecard+1
	ldy     #$08
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	ldy     #$00
	sta     (sreg),y
	inc     M0001
	bne     L0004
	inc     M0001+1
	jmp     L0004
L0018:	tya
	sta     M0001
	sta     M0001+1
L000C:	ldx     M0001+1
	cpx     #$02
	bcs     L000D
	lda     M0001
	clc
	adc     #<(_drivebuf1)
	sta     sreg
	lda     M0001+1
	adc     #>(_drivebuf1)
	sta     sreg+1
	lda     _drivecard+1
	sta     ptr1+1
	lda     _drivecard
	sta     ptr1
	lda     (ptr1),y
	sta     (sreg),y
	inc     M0001
	bne     L0011
	inc     M0001+1
L0011:	lda     M0001
	clc
	adc     #<(_drivebuf1)
	sta     sreg
	lda     M0001+1
	adc     #>(_drivebuf1)
	sta     sreg+1
	lda     _drivecard
	ldx     _drivecard+1
	ldy     #$08
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	ldy     #$00
	sta     (sreg),y
	inc     M0001
	bne     L000C
	inc     M0001+1
	jmp     L000C
L000D:	lda     _iochip
	ldx     _iochip+1
	clc
	adc     #$01
	bcc     L0013
	inx
L0013:	sta     sreg
	stx     sreg+1
	lda     _iochip
	ldx     _iochip+1
	iny
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	lsr     a
	dey
	sta     (sreg),y
	lda     _iochip
	ldx     _iochip+1
	iny
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	bne     L0015
	lda     _iochip+1
	sta     ptr1+1
	lda     _iochip
	sta     ptr1
	lda     #$80
	sta     (ptr1),y
L0015:	jmp     incsp1

.segment	"BSS"

M0001:
	.res	2,$00
M0002:
	.res	1,$00

.endproc

; ---------------------------------------------------------------
; void __near__ readSector (unsigned int sectorNum, unsigned char buf)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_readSector: near

.segment	"CODE"

	jsr     pusha
	lda     _drivecard+1
	sta     ptr1+1
	lda     _drivecard
	sta     ptr1
	ldy     #$01
	lda     (sp),y
	ldy     #$03
	sta     (ptr1),y
	lda     _drivecard
	ldx     _drivecard+1
	clc
	adc     #$04
	bcc     L0003
	inx
L0003:	sta     ptr1
	stx     ptr1+1
	dey
	lda     (sp),y
	ldy     #$00
	sta     (ptr1),y
	lda     _drivecard+1
	sta     ptr1+1
	lda     _drivecard
	sta     ptr1
	ldy     #$05
	lda     #$00
	sta     (ptr1),y
	lda     _drivecard+1
	sta     ptr1+1
	lda     _drivecard
	sta     ptr1
	iny
	lda     #$E0
	sta     (ptr1),y
	lda     _drivecard+1
	sta     ptr1+1
	lda     _drivecard
	sta     ptr1
	ldy     #$02
	lda     #$01
	sta     (ptr1),y
	lda     _drivecard+1
	sta     ptr1+1
	lda     _drivecard
	sta     ptr1
	ldy     #$07
	lda     #$20
	sta     (ptr1),y
	jsr     _busyWait
	lda     _drivecard
	ldx     _drivecard+1
	ldy     #$07
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	sta     M0001
	jsr     _drqWait
	ldy     #$00
	lda     (sp),y
	bne     L001B
	sta     M0002
	sta     M0002+1
L000A:	lda     M0002
	cmp     #$00
	lda     M0002+1
	sbc     #$02
	bvc     L000E
	eor     #$80
L000E:	jpl     L0014
	lda     M0002
	clc
	adc     #<(_drivebuf)
	sta     sreg
	lda     M0002+1
	adc     #>(_drivebuf)
	sta     sreg+1
	lda     _drivecard+1
	sta     ptr1+1
	lda     _drivecard
	sta     ptr1
	lda     (ptr1),y
	sta     (sreg),y
	inc     M0002
	bne     L0010
	inc     M0002+1
L0010:	lda     M0002
	clc
	adc     #<(_drivebuf)
	sta     sreg
	lda     M0002+1
	adc     #>(_drivebuf)
	sta     sreg+1
	lda     _drivecard
	ldx     _drivecard+1
	ldy     #$08
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	ldy     #$00
	sta     (sreg),y
	inc     M0002
	bne     L000A
	inc     M0002+1
	jmp     L000A
L001B:	tya
	sta     M0002
	sta     M0002+1
L0013:	lda     M0002
	cmp     #$00
	lda     M0002+1
	sbc     #$02
	bvc     L0017
	eor     #$80
L0017:	bpl     L0014
	lda     M0002
	clc
	adc     #<(_drivebuf1)
	sta     sreg
	lda     M0002+1
	adc     #>(_drivebuf1)
	sta     sreg+1
	lda     _drivecard+1
	sta     ptr1+1
	lda     _drivecard
	sta     ptr1
	lda     (ptr1),y
	sta     (sreg),y
	inc     M0002
	bne     L0019
	inc     M0002+1
L0019:	lda     M0002
	clc
	adc     #<(_drivebuf1)
	sta     sreg
	lda     M0002+1
	adc     #>(_drivebuf1)
	sta     sreg+1
	lda     _drivecard
	ldx     _drivecard+1
	ldy     #$08
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	ldy     #$00
	sta     (sreg),y
	inc     M0002
	bne     L0013
	inc     M0002+1
	jmp     L0013
L0014:	jmp     incsp3

.segment	"BSS"

M0001:
	.res	1,$00
M0002:
	.res	2,$00

.endproc

; ---------------------------------------------------------------
; void __near__ setMusicReg (unsigned char reg, unsigned char data)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_setMusicReg: near

.segment	"CODE"

	jsr     pusha
	lda     _musiccard+1
	sta     ptr1+1
	lda     _musiccard
	sta     ptr1
	ldy     #$01
	lda     (sp),y
	iny
	sta     (ptr1),y
	lda     _musiccard+1
	sta     ptr1+1
	lda     _musiccard
	sta     ptr1
	dey
	lda     #$0F
	sta     (ptr1),y
	lda     _musiccard+1
	sta     ptr1+1
	lda     _musiccard
	sta     ptr1
	lda     #$00
	sta     (ptr1),y
	lda     _musiccard+1
	sta     ptr1+1
	lda     _musiccard
	sta     ptr1
	dey
	lda     (sp),y
	ldy     #$02
	sta     (ptr1),y
	lda     _musiccard+1
	sta     ptr1+1
	lda     _musiccard
	sta     ptr1
	dey
	lda     #$0A
	sta     (ptr1),y
	lda     _musiccard+1
	sta     ptr1+1
	lda     _musiccard
	sta     ptr1
	lda     #$00
	sta     (ptr1),y
	jmp     incsp2

.endproc

; ---------------------------------------------------------------
; int __near__ delay (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_delay: near

.segment	"CODE"

	ldx     #$00
	lda     #$00
	sta     M0001
L0002:	ldx     #$00
	lda     M0001
	cmp     #$64
	jsr     boolult
	jne     L0005
	jmp     L0003
L0005:	nop
	ldx     #$00
	lda     M0001
	inc     M0001
	jmp     L0002
L0003:	ldx     #$00
	lda     #$00
	rts

.segment	"BSS"

M0001:
	.res	1,$00

.endproc

; ---------------------------------------------------------------
; void __near__ playSong (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_playSong: near

.segment	"CODE"

	lda     #$00
	sta     M0001
	sta     M0001+1
	sta     M0002
	sta     M0002+1
	sta     M0003
	sta     M0005
	lda     M0002
	ldx     M0002+1
	jsr     pushax
	lda     #$00
	jsr     _readSector
L0002:	lda     #$00
L0020:	sta     M0005
L0021:	lda     M0005
	cmp     #$0E
	jcs     L0023
	lda     M0003
	bne     L0009
	lda     #<(M0004)
	ldx     #>(M0004)
	clc
	adc     M0005
	bcc     L000A
	inx
L000A:	sta     sreg
	stx     sreg+1
	lda     M0001
	sta     ptr1
	lda     M0001+1
	clc
	adc     #>(_drivebuf)
	sta     ptr1+1
	ldy     #<(_drivebuf)
	lda     (ptr1),y
	ldy     #$00
	sta     (sreg),y
	inc     M0001
	bne     L000B
	inc     M0001+1
L000B:	lda     M0001+1
	bne     L000C
	lda     M0001
	cmp     #$01
	bne     L000C
	inc     M0002
	bne     L000E
	inc     M0002+1
L000E:	lda     M0002
	ldx     M0002+1
	jsr     _initStartSector
L000C:	lda     M0001
	cmp     #$00
	lda     M0001+1
	sbc     #$02
	bcc     L0022
	lda     #$01
	sta     M0003
	lda     #$00
	jmp     L0027
L0009:	lda     #<(M0004)
	ldx     #>(M0004)
	clc
	adc     M0005
	bcc     L0011
	inx
L0011:	sta     sreg
	stx     sreg+1
	lda     M0001
	sta     ptr1
	lda     M0001+1
	clc
	adc     #>(_drivebuf1)
	sta     ptr1+1
	ldy     #<(_drivebuf1)
	lda     (ptr1),y
	ldy     #$00
	sta     (sreg),y
	inc     M0001
	bne     L0012
	inc     M0001+1
L0012:	lda     M0001+1
	bne     L0013
	lda     M0001
	cmp     #$01
	bne     L0013
	inc     M0002
	bne     L0015
	inc     M0002+1
L0015:	lda     M0002
	ldx     M0002+1
	jsr     _initStartSector
L0013:	lda     M0001
	cmp     #$00
	lda     M0001+1
	sbc     #$02
	bcc     L0022
	lda     #$00
	sta     M0003
L0027:	sta     M0001
	sta     M0001+1
	lda     M0003
	jsr     _readDiskBuf
L0022:	inc     M0005
	jmp     L0021
L0023:	lda     #$00
	sta     M0005
L0024:	lda     M0005
	cmp     #$0E
	bcs     L0018
	jsr     pusha
	ldy     M0005
	lda     M0004,y
	jsr     _setMusicReg
	inc     M0005
	jmp     L0024
L0018:	lda     M0001
	ora     M0001+1
	jeq     L0020
	jsr     _delay
	jsr     _delay
	jsr     _delay
	jmp     L0002

.segment	"BSS"

M0001:
	.res	2,$00
M0002:
	.res	2,$00
M0003:
	.res	1,$00
M0004:
	.res	16,$00
M0005:
	.res	1,$00

.endproc

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	lda     #$00
	sta     M0002
	sta     M0003
	lda     _kbmem+1
	sta     ptr1+1
	lda     _kbmem
	sta     ptr1
	lda     #$00
	tay
	sta     (ptr1),y
	lda     _iochip+1
	sta     ptr1+1
	lda     _iochip
	sta     ptr1
	ldy     #$03
	lda     #$89
	sta     (ptr1),y
	lda     _iochip+1
	sta     ptr1+1
	lda     _iochip
	sta     ptr1
	ldy     #$01
	lda     #$80
	sta     (ptr1),y
	lda     _musiccard+1
	sta     ptr1+1
	lda     _musiccard
	sta     ptr1
	ldy     #$03
	lda     #$80
	sta     (ptr1),y
	lda     _musiccard+1
	sta     ptr1+1
	lda     _musiccard
	sta     ptr1
	lda     #$00
	tay
	sta     (ptr1),y
	lda     #$07
	jsr     pusha
	lda     #$3F
	jsr     _setMusicReg
	lda     #<(_text)
	ldx     #>(_text)
	jsr     _printText
	jsr     _setCursor
	lda     #$3E
	jsr     _dispChar
L0005:	lda     _kbmem+1
	sta     ptr1+1
	lda     _kbmem
	sta     ptr1
	ldy     #$00
	lda     (ptr1),y
	cmp     M0002
	beq     L0005
	inc     M0002
	lda     M0002
	cmp     #$20
	bne     L0009
	sty     M0002
L0009:	lda     _kbmem
	ldx     _kbmem+1
	ldy     M0002
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	sta     M0001
	cmp     #$F0
	bne     L0012
	lda     #$01
	sta     M0003
	jmp     L0005
L0012:	lda     M0003
	cmp     #$01
	bne     L000B
	lda     #$00
	sta     M0003
	jmp     L0005
L000B:	ldy     M0001
	lda     _ps2ToAscii,y
	sta     M0001
	cmp     #$69
	bne     L0013
	jsr     _readDiskInfo
L0013:	lda     M0001
	cmp     #$6D
	bne     L0014
	lda     #$00
	jsr     pusha
	lda     #$50
	jsr     _setMusicReg
	lda     #$01
	jsr     pusha
	lda     #$00
	jsr     _setMusicReg
	lda     #$08
	jsr     pusha
	lda     #$0F
	jsr     _setMusicReg
	lda     #$07
	jsr     pusha
	lda     #$3E
	jsr     _setMusicReg
L0014:	lda     M0001
	cmp     #$72
	bne     L0015
	jsr     push0
	jsr     _readSector
L0015:	lda     M0001
	cmp     #$70
	jne     L0005
	jsr     _playSong
	jmp     L0005

.segment	"BSS"

M0001:
	.res	1,$00
M0002:
	.res	1,$00
M0003:
	.res	1,$00

.endproc

